namespace Suss.TikTok.Client.Auth;

/// <summary>
/// Builds TikTok OAuth authorization URLs and exchanges returned authorization codes for tokens.
/// <para>
/// This service is intended for onboarding flows such as "Connect TikTok". Your web application
/// redirects the user to the generated authorization URL, receives the
/// callback from TikTok, validates the original state value, and calls
/// <see cref="ExchangeAuthorizationCodeAsync"/> with the returned code.
/// </para>
/// </summary>
public interface ITikTokOAuthService
{
    /// <summary>
    /// Builds the TikTok consent URL that a browser or QR code should open.
    /// </summary>
    /// <param name="redirectUri">The callback URI registered for the TikTok developer app.</param>
    /// <param name="state">An opaque anti-forgery/correlation value generated by the caller.</param>
    /// <param name="scopes">Optional OAuth scopes to request for this authorization.</param>
    /// <param name="additionalParameters">Optional TikTok-specific query parameters.</param>
    /// <returns>The absolute authorization URL.</returns>
    string BuildAuthorizationUrl(
        string redirectUri,
        string state,
        IEnumerable<string>? scopes = null,
        IReadOnlyDictionary<string, string?>? additionalParameters = null);

    /// <summary>
    /// Builds a TikTok consent URL for a specific authorization scenario.
    /// </summary>
    /// <param name="scenario">The scenario being started.</param>
    /// <param name="redirectUri">The callback URI registered for the TikTok developer app.</param>
    /// <param name="state">An opaque anti-forgery/correlation value generated by the caller.</param>
    /// <param name="scopes">Optional OAuth scopes to request for this authorization.</param>
    /// <param name="additionalParameters">Optional TikTok-specific query parameters.</param>
    /// <returns>The absolute authorization URL.</returns>
    string BuildAuthorizationUrl(
        TikTokAuthScenario scenario,
        string redirectUri,
        string state,
        IEnumerable<string>? scopes = null,
        IReadOnlyDictionary<string, string?>? additionalParameters = null);

    /// <summary>
    /// Exchanges a one-time authorization code from TikTok's callback for token data.
    /// </summary>
    /// <param name="authCode">The authorization code returned by TikTok.</param>
    /// <param name="cancellationToken">Token to cancel the exchange.</param>
    /// <returns>The token payload returned by TikTok.</returns>
    Task<TikTokOAuthTokenResult> ExchangeAuthorizationCodeAsync(
        string authCode,
        CancellationToken cancellationToken = default);

    /// <summary>
    /// Creates a customer-owned advertiser connection from an OAuth token result and selected
    /// advertiser id.
    /// </summary>
    /// <param name="token">The token result returned by <see cref="ExchangeAuthorizationCodeAsync"/>.</param>
    /// <param name="advertiserId">The customer advertiser id selected for this connection.</param>
    /// <returns>A connection record suitable for host-application storage.</returns>
    TikTokClientAdvertiserConnection CreateClientAdvertiserConnection(
        TikTokOAuthTokenResult token,
        string advertiserId);

    /// <summary>
    /// Creates one customer-owned advertiser connection for each advertiser id returned by TikTok.
    /// </summary>
    /// <param name="token">The token result returned by <see cref="ExchangeAuthorizationCodeAsync"/>.</param>
    /// <returns>Connection records suitable for host-application storage.</returns>
    IReadOnlyList<TikTokClientAdvertiserConnection> CreateClientAdvertiserConnections(
        TikTokOAuthTokenResult token);

    /// <summary>
    /// Returns the configured platform-owned advertiser connection used for managed-campaign flows.
    /// </summary>
    /// <returns>The managed advertiser id/token/identity configured for this app.</returns>
    TikTokManagedAdvertiserConnection GetManagedAdvertiserConnection();
}
